import type { DeviceResolutionPreset } from '../../types'

export const IPAD_RESOLUTION_PRESETS = [
  {
    id: 'ipad-legacy-1024x768',
    source: 'apple',
    category: 'ipad',
    label: 'iPad 9.7형·mini 7.9형 — 1024 × 768',
    width: 1024,
    height: 768,
    orientation: 'landscape',
    models: [
      'iPad 2',
      'iPad mini (1st generation)',
      'iPad mini 1',
    ],
    note:
      'iPad 2와 1세대 iPad mini의 기본 디스플레이 해상도를 가로 방향으로 저장한 프리셋입니다.',
  },
  {
    id: 'ipad-retina-2048x1536',
    source: 'apple',
    category: 'ipad',
    label: 'iPad Retina 9.7형·mini 7.9형 — 2048 × 1536',
    width: 2048,
    height: 1536,
    orientation: 'landscape',
    models: [
      'iPad (3rd generation)',
      'iPad 3',
      'iPad (4th generation)',
      'iPad 4',
      'iPad (5th generation)',
      'iPad 5',
      'iPad (6th generation)',
      'iPad 6',
      'iPad Air',
      'iPad Air (1st generation)',
      'iPad Air 1',
      'iPad Air 2',
      'iPad mini 2',
      'iPad mini 3',
      'iPad mini 4',
      'iPad mini (5th generation)',
      'iPad mini 5',
      'iPad Pro 9.7-inch',
    ],
    note:
      '여러 세대의 9.7형 iPad, 초기 iPad Air, Retina iPad mini 및 9.7형 iPad Pro가 사용하는 해상도입니다.',
  },
  {
    id: 'ipad-pro-10-5-2224x1668',
    source: 'apple',
    category: 'ipad',
    label: 'iPad 10.5형 — 2224 × 1668',
    width: 2224,
    height: 1668,
    orientation: 'landscape',
    diagonalInches: 10.5,
    models: [
      'iPad Pro 10.5-inch',
      'iPad Air (3rd generation)',
      'iPad Air 3',
    ],
    note:
      '10.5형 iPad Pro와 3세대 iPad Air가 사용하는 가로형 해상도입니다.',
  },
  {
    id: 'ipad-10-2-2160x1620',
    source: 'apple',
    category: 'ipad',
    label: 'iPad 10.2형 — 2160 × 1620',
    width: 2160,
    height: 1620,
    orientation: 'landscape',
    diagonalInches: 10.2,
    models: [
      'iPad (7th generation)',
      'iPad 7',
      'iPad (8th generation)',
      'iPad 8',
      'iPad (9th generation)',
      'iPad 9',
    ],
    note:
      '7세대부터 9세대까지의 10.2형 기본 iPad가 사용하는 가로형 해상도입니다.',
  },
  {
    id: 'ipad-mini-8-3-2266x1488',
    source: 'apple',
    category: 'ipad',
    label: 'iPad mini 8.3형 — 2266 × 1488',
    width: 2266,
    height: 1488,
    orientation: 'landscape',
    diagonalInches: 8.3,
    models: [
      'iPad mini (6th generation)',
      'iPad mini 6',
      'iPad mini (A17 Pro)',
    ],
    note:
      '6세대 iPad mini와 A17 Pro 탑재 iPad mini의 기본 해상도를 가로 방향으로 저장한 프리셋입니다.',
  },
  {
    id: 'ipad-10-9-11-2360x1640',
    source: 'apple',
    category: 'ipad',
    label: 'iPad 10.9형·11형 — 2360 × 1640',
    width: 2360,
    height: 1640,
    orientation: 'landscape',
    models: [
      'iPad Air (4th generation)',
      'iPad Air 4',
      'iPad Air (5th generation)',
      'iPad Air 5',
      'iPad Air 11-inch (M2)',
      'iPad Air 11-inch (M3)',
      'iPad Air 11-inch (M4)',
      'iPad (10th generation)',
      'iPad 10',
      'iPad (A16)',
      'iPad 11',
    ],
    note:
      '10.9형 iPad Air, 11형 iPad Air 및 최근 기본형 iPad가 사용하는 가로형 해상도입니다.',
  },
  {
    id: 'ipad-pro-11-2388x1668',
    source: 'apple',
    category: 'ipad',
    label: 'iPad Pro 11형 — 2388 × 1668',
    width: 2388,
    height: 1668,
    orientation: 'landscape',
    diagonalInches: 11,
    models: [
      'iPad Pro 11-inch (1st generation)',
      'iPad Pro 11-inch (2nd generation)',
      'iPad Pro 11-inch (3rd generation)',
      'iPad Pro 11-inch (4th generation)',
      'iPad Pro 11-inch (2018)',
      'iPad Pro 11-inch (2020)',
      'iPad Pro 11-inch (M1)',
      'iPad Pro 11-inch (M2)',
    ],
    note:
      '2018년부터 M2 세대까지의 11형 iPad Pro가 사용하는 가로형 해상도입니다.',
  },
  {
    id: 'ipad-pro-11-2420x1668',
    source: 'apple',
    category: 'ipad',
    label: 'iPad Pro 11형 — 2420 × 1668',
    width: 2420,
    height: 1668,
    orientation: 'landscape',
    diagonalInches: 11,
    models: [
      'iPad Pro 11-inch (M4)',
      'iPad Pro 11-inch (M5)',
    ],
    note:
      'M4 및 M5 세대 11형 iPad Pro의 기본 해상도를 가로 방향으로 저장한 프리셋입니다.',
  },
  {
    id: 'ipad-pro-12-9-13-2732x2048',
    source: 'apple',
    category: 'ipad',
    label: 'iPad Pro 12.9형·iPad Air 13형 — 2732 × 2048',
    width: 2732,
    height: 2048,
    orientation: 'landscape',
    models: [
      'iPad Pro 12.9-inch (1st generation)',
      'iPad Pro 12.9-inch (2nd generation)',
      'iPad Pro 12.9-inch (3rd generation)',
      'iPad Pro 12.9-inch (4th generation)',
      'iPad Pro 12.9-inch (5th generation)',
      'iPad Pro 12.9-inch (6th generation)',
      'iPad Pro 12.9-inch (2015)',
      'iPad Pro 12.9-inch (2017)',
      'iPad Pro 12.9-inch (2018)',
      'iPad Pro 12.9-inch (2020)',
      'iPad Pro 12.9-inch (M1)',
      'iPad Pro 12.9-inch (M2)',
      'iPad Air 13-inch (M2)',
      'iPad Air 13-inch (M3)',
      'iPad Air 13-inch (M4)',
    ],
    note:
      '모든 12.9형 iPad Pro 세대와 13형 iPad Air가 사용하는 가로형 해상도입니다.',
  },
  {
    id: 'ipad-pro-13-2752x2064',
    source: 'apple',
    category: 'ipad',
    label: 'iPad Pro 13형 — 2752 × 2064',
    width: 2752,
    height: 2064,
    orientation: 'landscape',
    diagonalInches: 13,
    models: [
      'iPad Pro 13-inch (M4)',
      'iPad Pro 13-inch (M5)',
    ],
    note:
      'M4 및 M5 세대 13형 iPad Pro의 기본 해상도를 가로 방향으로 저장한 프리셋입니다.',
  },
] as const satisfies readonly DeviceResolutionPreset[]