import type { DeviceResolutionPreset } from '../types'

export const GENERIC_DISPLAY_RESOLUTION_PRESETS = [
  {
    id: 'generic-fhd-portrait-1080x1920',
    source: 'generic',
    category: 'generic-display',
    label: 'Full HD 세로 — 1080 × 1920',
    width: 1080,
    height: 1920,
    orientation: 'portrait',
    models: [],
    note: '스마트폰 배경화면과 세로형 이미지에 널리 사용하는 9:16 해상도입니다.',
  },
  {
    id: 'generic-qhd-portrait-1440x2560',
    source: 'generic',
    category: 'generic-display',
    label: 'QHD 세로 — 1440 × 2560',
    width: 1440,
    height: 2560,
    orientation: 'portrait',
    models: [],
    note: '고해상도 스마트폰과 세로형 이미지에 사용할 수 있는 9:16 해상도입니다.',
  },
  {
    id: 'generic-fhd-landscape-1920x1080',
    source: 'generic',
    category: 'generic-display',
    label: 'Full HD 가로 — 1920 × 1080',
    width: 1920,
    height: 1080,
    orientation: 'landscape',
    models: [],
    note: '일반적인 노트북, 데스크톱 모니터 및 가로형 이미지에 사용하는 16:9 해상도입니다.',
  },
  {
    id: 'generic-qhd-landscape-2560x1440',
    source: 'generic',
    category: 'generic-display',
    label: 'QHD 가로 — 2560 × 1440',
    width: 2560,
    height: 1440,
    orientation: 'landscape',
    models: [],
    note: '고해상도 데스크톱 모니터에 널리 사용하는 16:9 해상도입니다.',
  },
  {
    id: 'generic-4k-uhd-landscape-3840x2160',
    source: 'generic',
    category: 'generic-display',
    label: '4K UHD 가로 — 3840 × 2160',
    width: 3840,
    height: 2160,
    orientation: 'landscape',
    models: [],
    note: '4K 모니터와 고해상도 가로형 이미지에 사용하는 16:9 해상도입니다.',
  },
] as const satisfies readonly DeviceResolutionPreset[]