import type { DeviceResolutionPreset } from '../types'
import {
  APPLE_DEVICE_RESOLUTION_PRESETS,
  IMAC_RESOLUTION_PRESETS,
  IPAD_RESOLUTION_PRESETS,
  IPHONE_RESOLUTION_PRESETS,
  MACBOOK_RESOLUTION_PRESETS,
} from './apple'
import { GENERIC_DISPLAY_RESOLUTION_PRESETS } from './genericDisplayPresets'
import {
  GALAXY_BOOK_RESOLUTION_PRESETS,
  GALAXY_PHONE_RESOLUTION_PRESETS,
  GALAXY_TAB_RESOLUTION_PRESETS,
  SAMSUNG_DEVICE_RESOLUTION_PRESETS,
  SAMSUNG_DISPLAY_RESOLUTION_PRESETS,
} from './samsung'

export {
  APPLE_DEVICE_RESOLUTION_PRESETS,
  GALAXY_BOOK_RESOLUTION_PRESETS,
  GALAXY_PHONE_RESOLUTION_PRESETS,
  GALAXY_TAB_RESOLUTION_PRESETS,
  GENERIC_DISPLAY_RESOLUTION_PRESETS,
  IMAC_RESOLUTION_PRESETS,
  IPAD_RESOLUTION_PRESETS,
  IPHONE_RESOLUTION_PRESETS,
  MACBOOK_RESOLUTION_PRESETS,
  SAMSUNG_DEVICE_RESOLUTION_PRESETS,
  SAMSUNG_DISPLAY_RESOLUTION_PRESETS,
}

export const ALL_RESOLUTION_PRESETS = [
  ...APPLE_DEVICE_RESOLUTION_PRESETS,
  ...SAMSUNG_DEVICE_RESOLUTION_PRESETS,
  ...GENERIC_DISPLAY_RESOLUTION_PRESETS,
] as const satisfies readonly DeviceResolutionPreset[]