-- =========================================================
-- Inyak Planner
-- Shared / curriculum database schema
-- =========================================================


-- ---------------------------------------------------------
-- 1. Courses
-- 실제 수강편람에서 수집한 강의
-- ---------------------------------------------------------

CREATE TABLE IF NOT EXISTS public.courses (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY
        PRIMARY KEY,

    academic_year INTEGER NOT NULL,
    semester INTEGER NOT NULL,
    track TEXT NOT NULL,

    course_code TEXT NOT NULL,
    course_name TEXT NOT NULL,
    section TEXT NOT NULL,

    completion_type TEXT,
    credits DOUBLE PRECISION,

    professor TEXT,
    department TEXT,
    recommended_year INTEGER,

    grading_method TEXT,
    competency_type TEXT,
    schedule_and_room TEXT,

    first_collected_at TIMESTAMPTZ,
    last_collected_at TIMESTAMPTZ,

    CONSTRAINT courses_academic_year_check
        CHECK (
            academic_year BETWEEN 2000 AND 2100
        ),

    CONSTRAINT courses_semester_check
        CHECK (
            semester IN (1, 2)
        ),

    CONSTRAINT courses_credits_check
        CHECK (
            credits >= 0
        ),

    CONSTRAINT courses_unique_offering
        UNIQUE (
            academic_year,
            semester,
            track,
            course_code,
            section
        )
);


-- ---------------------------------------------------------
-- 2. Curriculum courses
-- 학번별 공식 교육과정
-- ---------------------------------------------------------

CREATE TABLE IF NOT EXISTS public.curriculum_courses (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY
        PRIMARY KEY,

    entry_year INTEGER NOT NULL,

    grade INTEGER NOT NULL,
    semester INTEGER NOT NULL,

    course_name TEXT NOT NULL,
    course_code TEXT,

    completion_type TEXT NOT NULL,

    credits DOUBLE PRECISION,

    notes TEXT,

    CONSTRAINT curriculum_entry_year_check
        CHECK (
            entry_year BETWEEN 2000 AND 2100
        ),

    CONSTRAINT curriculum_grade_check
        CHECK (
            grade BETWEEN 1 AND 6
        ),

    CONSTRAINT curriculum_semester_check
        CHECK (
            semester IN (1, 2)
        ),

    CONSTRAINT curriculum_completion_type_check
        CHECK (
            completion_type IN (
                '전필',
                '전선'
            )
        ),

    CONSTRAINT curriculum_credits_check
        CHECK (
            credits >= 0
        )
);


-- ---------------------------------------------------------
-- 3. Major graduation requirements
-- 학번별 전공 졸업요건
-- ---------------------------------------------------------

CREATE TABLE IF NOT EXISTS public.graduation_requirements (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY
        PRIMARY KEY,

    entry_year INTEGER NOT NULL UNIQUE,

    major_required_credits
        DOUBLE PRECISION NOT NULL,

    major_elective_credits
        DOUBLE PRECISION NOT NULL,

    notes TEXT,

    CONSTRAINT graduation_entry_year_check
        CHECK (
            entry_year BETWEEN 2000 AND 2100
        ),

    CONSTRAINT graduation_required_credits_check
        CHECK (
            major_required_credits >= 0
        ),

    CONSTRAINT graduation_elective_credits_check
        CHECK (
            major_elective_credits >= 0
        )
);


-- ---------------------------------------------------------
-- 4. General education requirements
-- 교양 상위 요건
-- ---------------------------------------------------------

CREATE TABLE IF NOT EXISTS
public.general_education_requirements (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY
        PRIMARY KEY,

    entry_year INTEGER NOT NULL,

    category TEXT NOT NULL,

    minimum_credits DOUBLE PRECISION,

    minimum_area_count INTEGER,

    notes TEXT,

    display_order INTEGER NOT NULL DEFAULT 0,

    CONSTRAINT general_education_entry_year_check
        CHECK (
            entry_year BETWEEN 2000 AND 2100
        ),

    CONSTRAINT general_education_minimum_credits_check
        CHECK (
            minimum_credits IS NULL
            OR minimum_credits >= 0
        ),

    CONSTRAINT general_education_minimum_area_count_check
        CHECK (
            minimum_area_count IS NULL
            OR minimum_area_count >= 0
        )
);


-- ---------------------------------------------------------
-- 5. General education areas
-- 교양 세부 영역
-- ---------------------------------------------------------

CREATE TABLE IF NOT EXISTS
public.general_education_areas (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY
        PRIMARY KEY,

    requirement_id BIGINT NOT NULL,

    area_name TEXT NOT NULL,

    minimum_credits DOUBLE PRECISION,

    is_required BOOLEAN NOT NULL DEFAULT FALSE,

    notes TEXT,

    display_order INTEGER NOT NULL DEFAULT 0,

    CONSTRAINT general_education_areas_requirement_fk
        FOREIGN KEY (requirement_id)
        REFERENCES public.general_education_requirements(id)
        ON DELETE CASCADE,

    CONSTRAINT general_education_areas_minimum_credits_check
        CHECK (
            minimum_credits IS NULL
            OR minimum_credits >= 0
        )
);


-- =========================================================
-- Indexes
-- =========================================================

CREATE INDEX IF NOT EXISTS
    idx_courses_year_semester
ON public.courses(
    academic_year,
    semester
);


CREATE INDEX IF NOT EXISTS
    idx_courses_course_code
ON public.courses(
    course_code
);


CREATE INDEX IF NOT EXISTS
    idx_curriculum_courses_entry_year
ON public.curriculum_courses(
    entry_year
);


CREATE INDEX IF NOT EXISTS
    idx_curriculum_courses_entry_grade_semester
ON public.curriculum_courses(
    entry_year,
    grade,
    semester
);


CREATE INDEX IF NOT EXISTS
    idx_general_education_requirements_entry_year
ON public.general_education_requirements(
    entry_year
);


CREATE INDEX IF NOT EXISTS
    idx_general_education_areas_requirement
ON public.general_education_areas(
    requirement_id
);