-- =========================================================
-- Inyak Planner
-- Curriculum delivery timing rules
-- =========================================================

BEGIN;

CREATE TABLE IF NOT EXISTS
public.curriculum_delivery_rules (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY
        PRIMARY KEY,

    entry_year INTEGER NOT NULL,
    course_code TEXT NOT NULL,

    delivery_type TEXT NOT NULL,
    default_activity_period TEXT NOT NULL,
    allowed_activity_periods JSONB NOT NULL,

    consumes_regular_credit_limit
        BOOLEAN NOT NULL DEFAULT TRUE,

    notes TEXT,

    CONSTRAINT curriculum_delivery_rules_entry_year_check
        CHECK (entry_year BETWEEN 2000 AND 2100),

    CONSTRAINT curriculum_delivery_rules_type_check
        CHECK (
            delivery_type IN (
                'vacation_practicum',
                'flexible_practicum'
            )
        ),

    CONSTRAINT curriculum_delivery_rules_periods_check
        CHECK (
            jsonb_typeof(allowed_activity_periods) =
            'array'
        ),

    CONSTRAINT curriculum_delivery_rules_unique
        UNIQUE (entry_year, course_code)
);

CREATE INDEX IF NOT EXISTS
    idx_curriculum_delivery_rules_entry_year
ON public.curriculum_delivery_rules(entry_year);

INSERT INTO public.curriculum_delivery_rules (
    entry_year,
    course_code,
    delivery_type,
    default_activity_period,
    allowed_activity_periods,
    consumes_regular_credit_limit,
    notes
)
SELECT DISTINCT
    entry_year,
    course_code,
    'vacation_practicum',
    '5-summer',
    '["5-summer", "5-winter"]'::jsonb,
    TRUE,
    '실제 활동은 5학년 방학, 학점 인정은 공식 교육과정 학기 기준.'
FROM public.curriculum_courses
WHERE course_code IN (
    'ADA213',
    'ADA214',
    'ADA215',
    'ADA216',
    'ADA218',
    'ADA219',
    'ADA220'
)
ON CONFLICT (entry_year, course_code)
DO NOTHING;

INSERT INTO public.curriculum_delivery_rules (
    entry_year,
    course_code,
    delivery_type,
    default_activity_period,
    allowed_activity_periods,
    consumes_regular_credit_limit,
    notes
)
SELECT DISTINCT
    entry_year,
    course_code,
    'flexible_practicum',
    '6-1',
    '["6-1", "6-2"]'::jsonb,
    TRUE,
    '실제 활동은 6-1 또는 6-2, 학점 인정은 공식 6-2 기준.'
FROM public.curriculum_courses
WHERE course_code IN (
    'ADA226',
    'ADA227'
)
ON CONFLICT (entry_year, course_code)
DO NOTHING;

COMMIT;
